@startuml

/' Attori '/
:BotGestioneGalera: as BotGestioneGalera

/' Casi d'Uso '/
(Ammonisce Utente) as ammonisceUtente
(Dispone Ban All'Utente) as disponeBanAllUtente
(Revoca Ban All'Utente) as revocaBanAllUtente

/' Relazioni '/
BotGestioneGalera -left-> ammonisceUtente
BotGestioneGalera -up-> disponeBanAllUtente
BotGestioneGalera -right-> revocaBanAllUtente

@enduml
