@startuml

/' Attori '/
:BotGestioneUtenti: as BotGestioneUtenti

/' Casi d'Uso '/
(Aggiunge Utente Al Gruppo) as aggiungeUtenteAlGruppo
(Aggiunge Utente Al Canale) as aggiungeUtenteAlCanale
(Rimuove Utente Al Gruppo) as rimuoveUtenteAlGruppo
(Rimuove Utente Al Canale) as rimuoveUtenteAlCanale

/' Relazioni '/

BotGestioneUtenti -left-> aggiungeUtenteAlGruppo
BotGestioneUtenti -up-> aggiungeUtenteAlCanale
BotGestioneUtenti -right-> rimuoveUtenteAlGruppo
BotGestioneUtenti -down-> rimuoveUtenteAlCanale

@enduml
