@startuml

/' Attori '/
:BotGestioneAnnunci: as BotGestioneAnnunci

/' Casi d'Uso '/
(Pubblica Annuncio sul Canale) as pubblicaAnnuncioSulCanale
(Pubblica Annuncio Studente sul Canale) as pubblicaAnnuncioStudenteSulCanale
(Pubblica Annuncio Rappresentante sul Canale) as pubblicaAnnuncioRappresentanteSulCanale

/' Relazioni '/
pubblicaAnnuncioSulCanale -left-> pubblicaAnnuncioStudenteSulCanale : extends
pubblicaAnnuncioSulCanale -up-> pubblicaAnnuncioRappresentanteSulCanale : extends
BotGestioneAnnunci -up-> pubblicaAnnuncioSulCanale

@enduml
