@startuml

/' Attori '/
:Utente: as Utente
:Amministratore: as Amministratore
:Rappresentante: as Rappresentante

/' Casi d'Uso '/
/' Relazioni '/
Amministratore -up-|> Utente
Rappresentante -down-|> Utente

@enduml
